<a href="https://colab.research.google.com/github/JunyiJ/Flash-Kernels/blob/main/Triton_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive, userdata
import os

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Config (Fill these in)
try:
    GITHUB_TOKEN = userdata.get('GH_TOKEN')
    GITHUB_USER = "JunyiJ"
    REPO_NAME = "Flash-Kernels"
except userdata.SecretNotFoundError:
    print("❌ Secret 'GH_TOKEN' not found. Add it in the 'Secrets' tab (key icon).")

# 3. Clone or Sync
%cd /content/drive/MyDrive
if not os.path.exists(REPO_NAME):
    !git clone https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{REPO_NAME}.git
else:
    print(f"✅ {REPO_NAME} exists. Pulling latest changes...")
    %cd {REPO_NAME}
    !git pull

# 4. Set Git Identity
!git config --global user.email "jiaojunyi90@gmail.com"
!git config --global user.name "JunyiJ"

Mounted at /content/drive
/content/drive/MyDrive
✅ Flash-Kernels exists. Pulling latest changes...
/content/drive/MyDrive/Flash-Kernels
Already up to date.


In [2]:

%cd /content/drive/MyDrive/Flash-Kernels

/content/drive/MyDrive/Flash-Kernels


In [4]:
!python 01_vector_add/triton_vec_add.py

tensor([1.3713, 1.3076, 0.4940,  ..., 0.4024, 1.7918, 1.0686], device='cuda:0')
tensor([1.3713, 1.3076, 0.4940,  ..., 0.4024, 1.7918, 1.0686], device='cuda:0')
The maximum difference between torch and triton is 0.0


In [14]:
!python 02_matmul/triton_matmul.py

tensor([[ -0.6089,   5.5000,  -7.8633,  ...,  10.3594,  -2.4434,  -6.9180],
        [  7.0000,  16.2656,  26.4688,  ...,  11.8594,   4.5625,  18.3750],
        [  3.6777, -15.3125,  -2.0820,  ..., -41.7500,  26.8906, -12.5547],
        ...,
        [  0.7246,  75.0625, -26.1562,  ...,  26.6875,  -0.7197, -48.0000],
        [  6.6484,  -0.7490, -39.2500,  ..., -38.7812, -15.4609, -48.9688],
        [ 27.7812,  29.4062,  22.3281,  ...,  14.4922,   5.2344,  23.4844]],
       device='cuda:0', dtype=torch.float16)
tensor([[ -0.6089,   5.5000,  -7.8633,  ...,  10.3594,  -2.4434,  -6.9180],
        [  7.0000,  16.2656,  26.4688,  ...,  11.8594,   4.5625,  18.3750],
        [  3.6777, -15.3125,  -2.0820,  ..., -41.7500,  26.8906, -12.5547],
        ...,
        [  0.7246,  75.0625, -26.1562,  ...,  26.6875,  -0.7197, -48.0000],
        [  6.6484,  -0.7490, -39.2500,  ..., -38.7812, -15.4609, -48.9688],
        [ 27.7812,  29.4062,  22.3281,  ...,  14.4922,   5.2344,  23.4844]],
       device='

In [17]:
!python 03_softmax/triton_softmax.py

tensor([[0.0047, 0.0046, 0.0031,  ..., 0.0090, 0.0005, 0.0008],
        [0.0017, 0.0061, 0.0023,  ..., 0.0060, 0.0024, 0.0006],
        [0.0005, 0.0003, 0.0004,  ..., 0.0002, 0.0019, 0.0047],
        ...,
        [0.0011, 0.0073, 0.0009,  ..., 0.0010, 0.0035, 0.0007],
        [0.0033, 0.0021, 0.0116,  ..., 0.0009, 0.0030, 0.0002],
        [0.0030, 0.0017, 0.0004,  ..., 0.0005, 0.0003, 0.0024]],
       device='cuda:0')
tensor([[0.0047, 0.0046, 0.0031,  ..., 0.0090, 0.0005, 0.0008],
        [0.0017, 0.0061, 0.0023,  ..., 0.0060, 0.0024, 0.0006],
        [0.0005, 0.0003, 0.0004,  ..., 0.0002, 0.0019, 0.0047],
        ...,
        [0.0011, 0.0073, 0.0009,  ..., 0.0010, 0.0035, 0.0007],
        [0.0033, 0.0021, 0.0116,  ..., 0.0009, 0.0030, 0.0002],
        [0.0030, 0.0017, 0.0004,  ..., 0.0005, 0.0003, 0.0024]],
       device='cuda:0')
The maximum difference between torch and triton is 7.450580596923828e-09
True


In [29]:
!python 04_flash_attention/triton_flash_attn.py

tensor([[[[-1.6289e+00,  1.3203e+00,  1.5352e+00,  ..., -3.1270e+00,
           -2.8789e+00, -2.0264e-01],
          [-1.4160e-01, -7.3486e-02, -4.2310e-01,  ..., -2.2693e-01,
            2.3157e-01,  1.3457e+00],
          [-8.3691e-01,  6.8262e-01,  7.5732e-01,  ..., -1.7197e+00,
           -1.0166e+00,  3.6255e-01],
          ...,
          [ 6.5880e-03,  2.5620e-02,  1.0150e-01,  ..., -6.5660e-04,
           -6.3904e-02,  5.0171e-02],
          [-9.5459e-02, -4.0588e-02, -4.1466e-03,  ..., -2.6718e-02,
           -7.2083e-02,  4.0985e-02],
          [-3.7384e-03, -3.8391e-02,  9.7168e-02,  ..., -5.6580e-02,
           -1.1359e-01, -1.3229e-02]],

         [[ 2.0462e-02, -1.5664e+00, -9.5020e-01,  ..., -3.1421e-01,
           -3.7378e-01,  1.3809e+00],
          [ 6.0742e-01, -5.7031e-01, -8.9404e-01,  ...,  2.7539e-01,
           -6.0498e-01,  2.1436e-01],
          [ 3.5248e-02,  3.1616e-01,  3.5986e-01,  ...,  5.8057e-01,
           -1.0029e+00, -8.9062e-01],
          ...,
     

In [5]:
import sys
import os

# Ensure we are in the correct directory for relative imports
current_dir = os.getcwd()
expected_dir = '/content/drive/MyDrive/Flash-Kernels'

if current_dir != expected_dir:
    %cd {expected_dir}

# Add the directory containing the module to the Python path if it's not already there
module_path = './04_flash_attention'
if module_path not in sys.path:
    sys.path.insert(0, module_path)

# Now import the functions
from triton_flash_attn import flash_attn_forward

print("Successfully imported flash_attn_forward.")

tensor([[[[-1.6289e+00,  1.3203e+00,  1.5352e+00,  ..., -3.1270e+00,
           -2.8789e+00, -2.0264e-01],
          [-1.4160e-01, -7.3486e-02, -4.2310e-01,  ..., -2.2693e-01,
            2.3157e-01,  1.3457e+00],
          [-8.3691e-01,  6.8262e-01,  7.5732e-01,  ..., -1.7197e+00,
           -1.0166e+00,  3.6255e-01],
          ...,
          [ 6.5880e-03,  2.5620e-02,  1.0150e-01,  ..., -6.5660e-04,
           -6.3904e-02,  5.0171e-02],
          [-9.5459e-02, -4.0588e-02, -4.1466e-03,  ..., -2.6718e-02,
           -7.2083e-02,  4.0985e-02],
          [-3.7384e-03, -3.8391e-02,  9.7168e-02,  ..., -5.6580e-02,
           -1.1359e-01, -1.3229e-02]],

         [[ 2.0462e-02, -1.5664e+00, -9.5020e-01,  ..., -3.1421e-01,
           -3.7378e-01,  1.3809e+00],
          [ 6.0742e-01, -5.7031e-01, -8.9404e-01,  ...,  2.7539e-01,
           -6.0498e-01,  2.1436e-01],
          [ 3.5248e-02,  3.1616e-01,  3.5986e-01,  ...,  5.8057e-01,
           -1.0029e+00, -8.9062e-01],
          ...,
     

In [7]:
import triton
import triton.language as tl
import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

@triton.testing.perf_report(
    triton.testing.Benchmark(
        x_names=['BATCH', 'N_CTX'],  # Argument names to use as the x-axis
        x_vals=[1024, 2048],  # Sequence lengths from 1024 to 16384
        line_arg='provider',  # Argument name whose value corresponds to a different line in the plot
        line_vals=['triton', 'torch-native', 'torch-eager'],
        line_names=['Triton', 'Torch (Native)', 'Torch (Eager)'],
        styles=[('blue', '-'), ('green', '-'), ('red', '--')],
        ylabel='TFLOPS',
        plot_name='flash-attention-performance',
        args={'H': 8, 'D_MODEL': 64, 'sm_scale': 0.125},
    )
)
def benchmark(BATCH, N_CTX, H, D_MODEL, sm_scale, provider):
    q = torch.randn((BATCH, H, N_CTX, D_MODEL), device=DEVICE, dtype=torch.float16)
    k = torch.randn((BATCH, H, N_CTX, D_MODEL), device=DEVICE, dtype=torch.float16)
    v = torch.randn((BATCH, H, N_CTX, D_MODEL), device=DEVICE, dtype=torch.float16)

    quantiles = [0.5, 0.2, 0.8]
    if provider == 'torch-native':
        ms, min_ms, max_ms = triton.testing.do_bench(
            lambda: torch.nn.functional.scaled_dot_product_attention(q, k, v, is_causal=True, scale=sm_scale),
            quantiles=quantiles
        )
    if provider == 'triton':
        ms, min_ms, max_ms = triton.testing.do_bench(
            lambda: flash_attn_forward(q, k, v, sm_scale),
            quantiles=quantiles
        )
    if provider == 'torch-eager':
        # Manual implementation to show why Flash is better
        def eager_attn(q, k, v, scale):
            attn = (q @ k.transpose(-2, -1)) * scale
            # Simple causal mask for eager
            mask = torch.triu(torch.ones(N_CTX, N_CTX, device=DEVICE), diagonal=1).bool()
            attn = attn.masked_fill(mask, float('-inf'))
            return torch.softmax(attn, dim=-1) @ v

        ms, min_ms, max_ms = triton.testing.do_bench(
            lambda: eager_attn(q, k, v, sm_scale),
            quantiles=quantiles
        )

    # Compute TFLOPS
    # (2 ops for matmul 1, 2 ops for matmul 2) * Batch * Heads * Seq * Seq * Dim
    flops_per_matmul = 2.0 * BATCH * H * N_CTX * N_CTX * D_MODEL
    total_flops = 2 * flops_per_matmul
    return total_flops / (ms * 1e-3) / 1e12

# Run it!
benchmark.run(show_plots=True, print_data=True)

OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 GiB. GPU 0 has a total capacity of 14.56 GiB of which 5.23 GiB is free. Including non-PyTorch memory, this process has 9.33 GiB memory in use. Of the allocated memory 9.01 GiB is allocated by PyTorch, and 10.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)